name: Echo Context Information

on: workflow_dispatch

jobs:
  echo-variables:
    name: Echo context information
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          CUSTOM: hello from the env section!
        run: |
          echo Workflow ${{ github.workflow }} initiated by ${{ github.actor }}
          echo Workflow $GITHUB_WORKFLOW initiated by $GITHUB_ACTOR
          echo $CUSTOM
          echo $GITHUB_CONTEXT
