name: Echo Context Information

on: workflow_dispatch

jobs:
  echo-variables:
    name: Echo context information
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
